### ISSUE TITLE
Set only 2 selections in MultiSelectToggleGroup?  

### ISSUE THREAD

**Issue by IgordeOliveira** [nex3z/ToggleButtonGroup#15]
Eu queria selecionar 2 dias da semana usando MultiSelectToggleGroup, porem não vejo como limitar a quantidade de escolhas possiveis, é possivel ?

**Comment by nex3z** [comment]
MultiSelectToggleGroup does not support max selection settings for now.

**Comment by nex3z** [comment]
I've added this max selection feature in the 1.1.0 pre-release:

```
dependencies {
    compile 'com.nex3z:toggle-button-group:1.1.0'
}
```

Use the `app:tbgMaxSelect` attribute on `MultiSelectToggleGroup` to specify the max selection count, eg:

```xml
<com.nex3z.togglebuttongroup.MultiSelectToggleGroup
    android:id="@+id/group_weekdays"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:tbgChildSpacing="auto"
    app:tbgMaxSelect="3">

    ...

</com.nex3z.togglebuttongroup.MultiSelectToggleGroup>
```

In the layout above, when you select 3 buttons in `MultiSelectToggleGroup`, other buttons will be disabled until you deselect any of the selected buttons.
