### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by Arunbalaji001** [nex3z/ToggleButtonGroup#23]
I cannot get the selected button position, I am using flow label to create dynamic buttons from a string array as you written in your sample. How do I get the position of the button that is selected.
I tried to get the id of the button thought it would be sequential starting from 1, but it starts randomly.
I need to know whether first or last button or which button the user selected ?

**Comment by nex3z** [comment]
There is a solution provided in #20.

**Comment by Arunbalaji001** [comment]
I didn't see that.
Thank you so much for your help and for creating a wonderful library
