### ISSUE TITLE
OnCheckedChangeListener not called on unselecting the selected item

### ISSUE THREAD

**Issue by drunkendaddy** [nex3z/ToggleButtonGroup#24]
I've have a SingleSelectToggleGroup which contains two toggle buttons. On touching the selected item again, it gets unselected, but the OnCheckedChangeListener is not called? 

It get called called when selected for the first time or when I toggle selection but not when unselecting a selected item

I need it to be called for my requirements or even simply disable unsecting when touched again (allow toggle select other buttons)

I hope understood my issue. Please reply

**Comment by drunkendaddy** [comment]
Problem was I am using a custom toggle button, it is fixed once I override toggle()

```
@Override
    public void toggle() {
        if (isChecked()) {
            return;
        }
        super.toggle();
    }
```

You may close this issue

**Comment by nex3z** [comment]
The OnCheckedChangeListener notifies checked event (from unchecked to checked) of any button in SingleSelectToggleGroup.

By convention a radio group should have exactly one checked button in it. If you are using the built in [LabelToggle](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java) or [CircularToggle](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/CircularToggle.java), this is ensured by setting [radioStyle](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/MarkerButton.java#L67) to true when they are being added to SingleSelectToggleGroup, as shown [here](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/SingleSelectToggleGroup.java#L47). Similar approach can be found in [RadioButton](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/RadioButton.java#75), which forbids checked button to be unchecked.

If you want to uncheck buttons in SingleSelectToggleGroup, you can built your custom button and handle the checked/unchecked state on the button yourself. 

You can also use MultiSelectToggleGroup, the [OnCheckedStateChangeListener](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/MultiSelectToggleGroup.java#L83) will notify any change, but you will need extra logic to uncheck previous button.
