### ISSUE TITLE
 Circular Background size and text color 

### ISSUE THREAD

**Issue by GhadahMat** [nex3z/ToggleButtonGroup#25]
Hello, 

I’m using the SingleSelectToggleGroup and I tried to change the text color from black to another, the android: textColor= “”. Worked but when I click on one of the buttons the color do not change to white. 

Also one of the buttons text is kind of long length (“women”) when I click on it the circle background doesn’t fit the entire word. I tried to set the length of height and width but nothing changed. 

Waiting for your help and thank you so much for the grate library 🌷

**Comment by nex3z** [comment]
You can use a color selector to sepcify different text color for checked and unchecked state. For example, add a `selector_text_black_orange.xml` to `/res/color`  directory with the following content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true" android:color="#FFFF5722"/>
    <item android:color="#FF212121"/>
</selector>
```

Then set `android:textColor="@color/selector_text_black_orange"`:

```xml
<com.nex3z.togglebuttongroup.button.CircularToggle
    android:id="@+id/woman"
    android:layout_width="64dp"
    android:layout_height="64dp"
    android:textSize="16sp"
    android:text="woman"
    android:textColor="@color/selector_text_black_orange"
    app:tbgMarkerColor="#FFFFC107"/>
```

This will produce:

![device-2018-03-24-104409](https://user-images.githubusercontent.com/5645004/37859594-2366a0a2-2f51-11e8-8095-a66b14a95eb8.png)

**Comment by GhadahMat** [comment]
it's working thank you so much
