### ISSUE TITLE
Custom font for the toggle button text

### ISSUE THREAD

**Issue by drunkendaddy** [nex3z/ToggleButtonGroup#26]
It'd be really good if we could custom font for the buttons without creating a custom button

**Comment by nex3z** [comment]
I've added a `getTextView()` method to retrieve the TextView in `CircularToggle` and `MarkerButton` in v1.1.3.

```
implementation 'com.nex3z:toggle-button-group:1.1.3'
```

```java
CircularToggle toggle = findViewById(R.id.choice_a);
toggle.getTextView().setTextSize(24);
```

**Comment by djdance** [comment]
it works!
I suppose, it should be added to the start page.

for whose who will search for FontAwesom implementation.

Copy fontawesome.ttf to /res/font

TypeFace fontawesome = ResourcesCompat.getFont(getApplicationContext(), R.font.fontawesome);
((LabelToggle)rootView.findViewById(R.id.choice_e)).getTextView().setTypeface(fontawesome);

<com.nex3z.togglebuttongroup.button.LabelToggle
                    android:id="@+id/choice_e"
....
                    android:textColor="@color/colorPrimary"    <<--- don't forget! 
                    android:text="\uf2ed"/>
