### ISSUE TITLE
Possible to have different colors for border and background color when selected?

### ISSUE THREAD

**Issue by drunkendaddy** [nex3z/ToggleButtonGroup#27]

**Comment by nex3z** [comment]
If you are using [`CircularToggle`](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/CircularToggle.java), you can use [`setCheckedImageDrawable(Drawable drawable)`](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/MarkerButton.java#L121) to change the default background for the checked state. 

```
CircularToggle toggle = findViewById(R.id.choice_a);
toggle.setCheckedImageDrawable(ContextCompat.getDrawable(this, R.drawable.bg_circle));
```

Please feel free to build your own custom button that best suits your needs.
