### ISSUE TITLE
MultiSelectToggleGroup with Minimum Select Count

### ISSUE THREAD

**Issue by lucblender** [nex3z/ToggleButtonGroup#28]
With using a MultiSelectToggleGroup, we can set a maximum select count with setMaxSelectCount but we can't "setMinSelectCount".

I tried to force the re-check of a LabelToggle in the OnCheckedChangeListener, and it doesn't update the UI of the MultiSelectToggleGroup but if using the getCheck of LabelToggle, it's state as changed.

**Comment by nex3z** [comment]
There was an issue with the order of the checked state notification, fixed in the v1.1.4 version.
```
compile 'com.nex3z:toggle-button-group:1.1.4'
```

![demo](https://user-images.githubusercontent.com/5645004/38689514-73391cb0-3eae-11e8-8f54-671c2f931acc.gif)
