### ISSUE TITLE
get the string

### ISSUE THREAD

**Issue by alfaaluska** [nex3z/ToggleButtonGroup#3]
how do i define the selected text on string like:

` SingleSelectToggleGroup nominal = (SingleSelectToggleGroup) findViewById(R.id.nominal);`

i've tried
`String choosennominal = nominal.getCheckedPositions().toString();`
and
`String choosennominal = nominal.getTextButtons().toString();`

but i still don't get the button text, help me please

**Comment by alfaaluska** [comment]
<img src="https://github.com/nex3z/ToggleButtonGroup/raw/master/images/single.gif"/>

this is the example:
i want to get the "A" "B" "C" "D" not the position, how to do it?

**Comment by nex3z** [comment]
Hi alfaaluska, `ToggleButtonGroup` doesn't have a method to get the button text by position. I'll try to add a convenient method in the next release.

For now you can get the button text from the data source:
```java
final SingleSelectToggleGroup singleSelect =
        (SingleSelectToggleGroup) findViewById(R.id.single_selection_group);
final String[] choices = getResources().getStringArray(R.array.choices);
final List<String> choicesList = new ArrayList<>(Arrays.asList(choices));
singleSelect.setButtons(choicesList);

singleSelect.setOnCheckedChangeListener(new ToggleButtonGroup.OnCheckedChangeListener() {
    @Override
    public void onCheckedChange(int position, boolean isChecked) {
        String selectedText = choicesList.get(position);
    }
});
```
If you have the data source (`choicesList`) and the selected position (`position`), then you can get the text on the selected button from data source (`choicesList.get(position))`.

**Comment by alfaaluska** [comment]
It perfectly works, but the default selected text will be declared as `null`.

**Comment by nex3z** [comment]
For `SingleSelectToggleGroup`, the default selected button will be  [the first button in the group](https://github.com/nex3z/ToggleButtonGroup/blob/f7806e622294a5d615f0b33f630f6d8710ed0a28/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/SingleSelectToggleGroup.java#L35), so you can assume that the default selected text is the text on the first button.

```java
private String mSelectedText;

private void setupSingleSelectToggleGroup() {
    final SingleSelectToggleGroup singleSelect =
            (SingleSelectToggleGroup) findViewById(R.id.single_selection_group);

    final String[] choices = getResources().getStringArray(R.array.choices);
    final List<String> choicesList = new ArrayList<>(Arrays.asList(choices));
    singleSelect.setButtons(choicesList);

    // The defult selected button is the first button in the group
    mSelectedText = choicesList.get(0);

    singleSelect.setOnCheckedChangeListener(new ToggleButtonGroup.OnCheckedChangeListener() {
        @Override
        public void onCheckedChange(int position, boolean isChecked) {
            mSelectedText = choicesList.get(position);
        }
    });
}
```

You can also call `setCheckedAt()` on `SingleSelectToggleGroup` instance (`singleSelect `) to set other button as default selection, just remember to update the local storage of the selected text (`mSelectedText`) accordingly.

```java
singleSelect.setCheckedAt(2, true);
mSelectedText = choicesList.get(2);
```

For the multi-select scenario, as user can select an arbitrary number of buttons, so `MultiSelectToggleGroup` does not assume any default selection. I think it's OK to initialize the selected texts to be null or an empty collection. If you need any buttons to be selected by default, you can use`setCheckedPositions()` or `setCheckedAt()` on `MultiSelectToggleGroup`.

**Comment by alfaaluska** [comment]
Thanks a lot for your explanation, it works well 👍
