### ISSUE TITLE
How to add icon to button?

### ISSUE THREAD

**Issue by leslieharland** [nex3z/ToggleButtonGroup#30]
An alternative for setCompoundDrawablesWithIntrinsicBounds

**Comment by nex3z** [comment]
You can change the background of  [`CircularToggle`](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/CircularToggle.java) by using  [`setCheckedImageDrawable(Drawable drawable)`](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/MarkerButton.java#L121), as described in #27. For further customization , feel free to build your own custom button.
