### ISSUE TITLE
Setting text programmatically

### ISSUE THREAD

**Issue by voximodo** [nex3z/ToggleButtonGroup#32]
Hello,
thanks for a great work with this library :)
One question - is it possible to set button text programmatically?
With regards,

**Comment by nex3z** [comment]
You can use the [`setText()`](https://github.com/nex3z/ToggleButtonGroup/blob/master/sample/src/main/java/com/nex3z/togglebuttongroup/sample/FlowLabelActivity.java#L34) method to set button text.
