### ISSUE TITLE
bold text in CircularToggle button

### ISSUE THREAD

**Issue by hscoraline** [nex3z/ToggleButtonGroup#34]
i can't set bold style text in CircularToggle button T_T , how to set it?
sorry for my English!

**Comment by nex3z** [comment]
Call `getTextView()` on `CircularToggle` to retrieve the embedded `TextView`, then use [`setTypeface(Typeface tf, int style)`](https://developer.android.com/reference/android/widget/TextView.html#setTypeface(android.graphics.Typeface,%20int)) to set text style.

```java
CircularToggle toggle = findViewById(R.id.choice_a);
toggle.getTextView().setTypeface(Typeface.DEFAULT, Typeface.BOLD);
```
