### ISSUE TITLE
A method to check if a button is checked.

### ISSUE THREAD

**Issue by YogevUzan** [nex3z/ToggleButtonGroup#35]
Hi,
Can you please add a isChecked method? 
Something like this

> boolean isChecked= toggleGroup.isButtonChecked(int id)?

**Comment by nex3z** [comment]
I've added a `isChecked(int childId)` method in version `1.1.5`. Try 
```
implementation 'com.nex3z:toggle-button-group:1.1.5'
```

```java
boolean isChecked = toggleGroup.isChecked(childId);
```

**Comment by YogevUzan** [comment]
Oh, you might want to change the version in the main page.
Thank you very much!!
