### ISSUE TITLE
Can not check a ToggleButton without triggering events

### ISSUE THREAD

**Issue by wushexu** [nex3z/ToggleButtonGroup#37]
我使用ToggleButtonGroup时需要设置初始状态，不希望触发事件，调用

> void check(int id)

结果还是触发了 ToggleButtonGroup.OnCheckedChangeListener 的事件。
查代码发现，check(int id)的确调了`setCheckedId(id, false)`（传了false不触发事件）
然而调的`void setCheckedStateForView(int viewId, boolean checked)` 转而调child的setChecked：

> ((Checkable) target).setChecked(checked)

在CompoundToggleButton的setChecked实现中，异步触发了OnCheckedChangeListener事件，这个OnCheckedChangeListener的实现就在ToggleButtonGroup及其子类中。在ToggleButtonGroup中则有：

>     @Override
>     protected <T extends View & Checkable> void onChildCheckedChange(T child, boolean isChecked) {
>         if (isChecked) {
>             if (mCheckedId != View.NO_ID && mCheckedId != child.getId()) {
>                 setCheckedStateForView(mCheckedId, false);
>             }
>             int id = child.getId();
>             setCheckedId(id);
>         }
>     }

上面的setCheckedId(id)触发了事件。

另外，SingleSelectToggleGroup如果在layout中设初始值也是触发事件的。这是否有必要？或者是否可以让用户选择？

**Comment by nex3z** [comment]
我在 1.1.7 版本为 `ToggleButtonGroup` 加入了一个 `android:checkedButton` 属性，可以不触发事件地设置初始状态。

```
compile 'com.nex3z:toggle-button-group:1.1.7'
```

```xml
<com.nex3z.togglebuttongroup.SingleSelectToggleGroup
    android:id="@+id/group_choices"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:checkedButton="@+id/choice_a">

    <com.nex3z.togglebuttongroup.button.CircularToggle
        android:id="@+id/choice_a"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="16sp"
        android:text="A"/>

    <!--...-->

</com.nex3z.togglebuttongroup.SingleSelectToggleGroup>
```

**Comment by wushexu** [comment]
感谢！对于编程创建的SingleSelectToggleGroup来说，似乎还是没有不触发事件的初始化方法？是否可以加个addView的重载来支持？
奇怪为什么代码不更新到github了呢？

**Comment by nex3z** [comment]
更新到 b9b192aeaf9f69c99656dbceae47c9bfb34d5a26

`check()` 会触发 `OnCheckedChangeListener`，与 `RadioGroup` 保持一致。

`CompoundToggleButton` 的 checked 事件是异步回调的，如果不希望处理 App 界面初始化时的 checked 事件，可以定义一个额外的 flag 来在 `OnCheckedChangeListener` 的 `onCheckedChanged()` 回调里跳过初始化期间的 checked 事件；或者自定义一个同步回调 checked 事件的按钮，在 App 界面初始化完成后再为 `SingleSelectToggleGroup` 添加 `OnCheckedChangeListener`。

**Comment by wushexu** [comment]
我这么改了一下：

1. `CompoundToggleButton`，把异步改为同步。由于异步也是在ui线程，异步没多大必要。

>         if (mChecked != checked) {
>             mChecked = checked;
> 
>             if (mOnCheckedWidgetListener != null) {
>                 mOnCheckedWidgetListener.onCheckedChanged(CompoundToggleButton.this, mChecked);
>             }
>         }

2. `SingleSelectToggleGroup`，增加属性changeListenerEnabled（以及相应的setter/getter方法，如果不想暴露就去掉），用它来控制是否触发事件：

> private boolean changeListenerEnabled = true;

修改onChildCheckedChange：
>     @Override
>     protected <T extends View & Checkable> void onChildCheckedChange(T child, boolean isChecked) {
>         if (isChecked) {
>             ...
>             if (!changeListenerEnabled) {
>                 setCheckedId(id, false);
>             } else {
>                 ...
>             }
>         }
>     }

增加checkSilently方法：
>     public void checkSilently(int id) {
>         boolean saved = changeListenerEnabled;
>         try {
>             changeListenerEnabled = false;
>             check(id);
>         } finally {
>             changeListenerEnabled = saved;
>         }
>     }
