### ISSUE TITLE
'checkedId' in onCheckedChanged()

### ISSUE THREAD

**Issue by Sultan91** [nex3z/ToggleButtonGroup#39]
I have problem with checkedID when setting setOnCheckedChangeListener() checkedID does not resets after activity has finished and reopened once again checkedID grows

**Comment by nex3z** [comment]
This is an expected behaviour. When you did not assign an id to a button, ToggleButtonGroup will [generate an id](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/ToggleButtonGroup.java#L151) during initialization, which does not guarantee to be the same at each run.

If you want a "static" id for each button, please assgin the id attribute for the button, for example:

```xml
<com.nex3z.togglebuttongroup.button.CircularToggle
    android:id="@+id/choice_a"  <- assign android:id attribute
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:textSize="16sp"
    android:text="A"/>
```
In this way, the id will not change at each run, but still may change across different build. You may want to use id name (like `choice_a` from above) instead of specific id value (like `2131296300`).

**Comment by Sultan91** [comment]
Thanks for reply!, What about if I need create CircularToggle button dynamically in java code:
`CircularToggle toggle = new CircularToggle(this);`
`toggle.setId();`
Allows to set an ID, which AFAIK  should be already defined in layout. There is no other way to define button ID without pre-creating layout elmement

**Comment by nex3z** [comment]
You can use create button with specific id and add it to the button group:

```java
SingleSelectToggleGroup single = findViewById(R.id.group_choices);
CircularToggle toggle = new CircularToggle(this);
toggle.setId(123); // set button id
toggle.setText("test");
single.addView(toggle); // add button to SingleSelectToggleGroup
```

It's better to give each button a unique id if you would like to retrieve them by `findViewById()` later.

**Comment by Sultan91** [comment]
Yes but `toggle.setId(123)` requires R.id. element(which is usually quite big number) not a simple integer

**Comment by nex3z** [comment]
Technically all [`setId()`](https://developer.android.com/reference/android/view/View#setId(int)) needs is a positive number. You can also use [`generateViewId()`](https://developer.android.com/reference/android/view/View#generateViewId%28%29) for a long and unique id, or use [id resource](https://stackoverflow.com/a/8937477) to predefine unique id to be used later.

**Comment by zoro238** [comment]
> 
> 
> This is an expected behaviour. When you did not assign an id to a button, ToggleButtonGroup will [generate an id](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/ToggleButtonGroup.java#L151) during initialization, which does not guarantee to be the same at each run.
> 
> If you want a "static" id for each button, please assgin the id attribute for the button, for example:
> 
> ```
> <com.nex3z.togglebuttongroup.button.CircularToggle
>     android:id="@+id/choice_a"  <- assign android:id attribute
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:textSize="16sp"
>     android:text="A"/>
> ```
> 
> In this way, the id will not change at each run, but still may change across different build. You may want to use id name (like `choice_a` from above) instead of specific id value (like `2131296300`).

how can I . I mean choice_a Check
pls code sample

**Comment by nex3z** [comment]
> > This is an expected behaviour. When you did not assign an id to a button, ToggleButtonGroup will [generate an id](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/ToggleButtonGroup.java#L151) during initialization, which does not guarantee to be the same at each run.
> > If you want a "static" id for each button, please assgin the id attribute for the button, for example:
> > ```
> > <com.nex3z.togglebuttongroup.button.CircularToggle
> >     android:id="@+id/choice_a"  <- assign android:id attribute
> >     android:layout_width="wrap_content"
> >     android:layout_height="wrap_content"
> >     android:textSize="16sp"
> >     android:text="A"/>
> > ```
> > In this way, the id will not change at each run, but still may change across different build. You may want to use id name (like `choice_a` from above) instead of specific id value (like `2131296300`).
> 
> how can I . I mean choice_a Check
> pls code sample

```xml
CircularToggle choiceA = findViewById(R.id.choice_a);
choiceA.setChecked(true);
```

Please create different issue for different question.

**Comment by zoro238** [comment]
THANK YOU
