### ISSUE TITLE
center the buttons

### ISSUE THREAD

**Issue by alfaaluska** [nex3z/ToggleButtonGroup#4]
I want to make this:
![screenshot_2017-04-15-23-33-07](https://cloud.githubusercontent.com/assets/21968935/25065159/3a2956fc-2234-11e7-90b0-b2ec50a7604a.png)

looks like this:
![screenshot_2017-04-15-23-33-07xx](https://cloud.githubusercontent.com/assets/21968935/25065178/b8b751ea-2234-11e7-919d-178fa068c9ed.png)

P.S.:  I edited it with Paint, so it is not really fit to center.

I've tried to add `android:gravity="center_horizontal"` with  `app:tbgButtonSpacing="auto"` inside the `ToggleButtonGrop` but it doesn't work.

I've tried to set  `app:tbgButtonSpacing="5dp"` but it won't center the buttons, even I added the `"android:gravity="center_horizontal"`

Thanks before

**Comment by nex3z** [comment]
The ToggleButtonGroup does not support gravity configuration for a specific line. But it do provide a `app:tbgButtonSpacingForLastRow` attribute for the buttons in the last row separately. Set `app:tbgButtonSpacingForLastRow`  to `align` for a better alignment. For the detailed usage, please refer to the "Tag Sample" part in the provided sample, hope it meets your requirement.
