### ISSUE TITLE
Change LabelToggle background and border color for checked/unchecked state programmatically?

### ISSUE THREAD

**Issue by usmaan-anwar** [nex3z/ToggleButtonGroup#40]
Hi @nex3z ,
Thanks for developing such a great library. I am using your library in my project, I would like to know how I can simply just use my own background and border color and everything else the same.
Currently i am doing something like this:

```
private void initMultiSelectToggleGroup() {
        MultiSelectToggleGroup interestsMultiSelectToggleGroup = findViewById(R.id.interests_multi_select_toggle_group);
        String[] interests = {"Photography", "Hiking", "Skiing"};
        for (String interest : interests) {
            LabelToggle toggle = new LabelToggle(this);
            toggle.setText(interest);
            toggle.setMarkerColor(R.color.colorPrimaryLight);
            interestsMultiSelectToggleGroup.addView(toggle);
        }
    }
```

But with this I am getting a greyish border and background color instead of my defined `colorPrimaryLight`.

**PS: You mentioned that we can use our custom buttons, but just for changing the background and border color, I don't think creating a whole new custom button is a good idea, plus I (beginner) am confused on how I can create a custom button (Complete Steps to create a custom button) . Please help me with this** 

Thanks in advance.

**Comment by nex3z** [comment]
When calling `setMarkerColor()`, pass a color value instead of a color resource id (e.g. `R.color.colorPrimaryLight`). 

You can get color value from color resource id by [`ContextCompat.getColor()`](https://developer.android.com/reference/android/support/v4/content/ContextCompat#getcolor).

For examlpe, 
```java
MultiSelectToggleGroup interestsMultiSelectToggleGroup = findViewById(R.id.interests_multi_select_toggle_group);
String[] interests = {"Photography", "Hiking", "Skiing"};
for (String interest : interests) {
    LabelToggle toggle = new LabelToggle(this);
    toggle.setText(interest);
    toggle.setMarkerColor(ContextCompat.getColor(this, R.color.colorPrimaryLight)); // get actual color value from resource id
    interestsMultiSelectToggleGroup.addView(toggle);
}
```
will give you
![device-2018-10-06-214513](https://user-images.githubusercontent.com/5645004/46571986-362b4580-c9b1-11e8-9f0c-83598eab516e.png)

**Comment by usmaan-anwar** [comment]
Thanks a lot Man, works perfect.
The owners of libraries usually don't help this much like you do.
Can I have one more question here, or should I create a separate issue?

**Comment by nex3z** [comment]
Of course.

**Comment by usmaan-anwar** [comment]
Actually I am using your library to let the user select their "Interests", I am programmatically creating the interests and save the selected one on server as strings, then when a user logs in I get his interests as strings, I just want to know how can set checked on those buttons which user has selected using the string values?
Thanks a lot for your help!
