### ISSUE TITLE
load text in side CicrualrToggle Button programmatically

### ISSUE THREAD

**Issue by zoro238** [nex3z/ToggleButtonGroup#45]
How do you put the text of their income
Programmatically

**Comment by nex3z** [comment]
Please check #32. [setText()](https://github.com/nex3z/ToggleButtonGroup/blob/master/sample/src/main/java/com/nex3z/togglebuttongroup/sample/FlowLabelActivity.java#L34) works for both CircularToggle and LabelToggle.
