### ISSUE TITLE
androidx version

### ISSUE THREAD

**Issue by dpreussler** [nex3z/ToggleButtonGroup#46]
Hi, can you provide a jetpack version?
We already migrated and dont want to add dependency to pre androidx artefacts

**Comment by nex3z** [comment]
Of course.
```
implementation 'com.nex3z:toggle-button-group-x:0.1.0'
```

**Comment by dpreussler** [comment]
thank you

**Comment by ytheekshana** [comment]
So you are going to update x version too right?

**Comment by vkotovv** [comment]
@nex3z I think this should be included in Readme.

**Comment by nex3z** [comment]
@vkotovv I've updated readme with both version. Further realease will be based on AndroidX.
