### ISSUE TITLE
Removing border color of LabelToggle?

### ISSUE THREAD

**Issue by sadiqrazasyed** [nex3z/ToggleButtonGroup#49]
Hey, great library!
I couldn't find an option to remove the border from LabelToggle.
CircularToggle seems to have it in default but I prefer the LabelToggle, due to its shape.
Any help is appreciated.

**Comment by nex3z** [comment]
You can build a custom button by copying the code from [LabelToggle.java](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java) and comment out [line 63](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java#L63) and [line 69](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java#L69), like

```java
private void initBackground() {
    GradientDrawable checked = new GradientDrawable();
    checked.setColor(mMarkerColor);
    checked.setCornerRadius(dpToPx(25));
    // checked.setStroke(1, mMarkerColor);
    mIvBg.setImageDrawable(checked);

    GradientDrawable unchecked = new GradientDrawable();
    unchecked.setColor(ContextCompat.getColor(getContext(), android.R.color.transparent));
    unchecked.setCornerRadius(dpToPx(25));
    // unchecked.setStroke((int) dpToPx(1), mMarkerColor);
    mTvText.setBackgroundDrawable(unchecked);
}
```

![device-2019-04-01-190740](https://user-images.githubusercontent.com/5645004/55323784-ade6b280-54b2-11e9-97a7-c8e37729eca1.png)

**Comment by sadiqrazasyed** [comment]
Thanks for the quick response. Works like charm!
