### ISSUE TITLE
Get the specific item position

### ISSUE THREAD

**Issue by lordfarhan** [nex3z/ToggleButtonGroup#50]
First operation, it showed a true position, ex : 1, 2, 3, 4, 5, 6, 7. But the next operation it showed a wrong position, ex : 8, 9, 10, 11, 12, 13, 14.  And after I closed the app, then I opened it again, it was added by 7, ex : 15, 16, 17, 18, 19, 20, 21. The first number always added by 7 after restarting app. But after I forced stop the app and then open it again, it showed a true position again.

**Comment by nex3z** [comment]
How did you retrieve the position? Could you please share your code snippet for further analysis?

**Comment by lordfarhan** [comment]
`
multiDays = findViewById(R.id.multiSelectToggleGroup_day);
        String[] daysArray = getResources().getStringArray(R.array.days);
        for (String text : daysArray) {
            LabelToggle toggle = new LabelToggle(this);
            toggle.setText(text);
            toggle.setMarkerColor(getResources().getColor(R.color.colorPrimary));
            multiDays.addView(toggle);
        }
`
Here I retrieved the position.
`
Set<Integer> daysCheckedIds = multiDays.getCheckedIds();
            selectedDays = utils.convertSetIntegerToIntArray(daysCheckedIds);

            String days = utils.convertIntArrayToString(selectedDays);
`

**Comment by lordfarhan** [comment]
![image](https://user-images.githubusercontent.com/37336569/58758915-d8a1c580-854c-11e9-8695-1bd212a8087c.png)

And this how I retrieved the position
![image](https://user-images.githubusercontent.com/37336569/58758924-ec4d2c00-854c-11e9-9252-b6c8903bc14d.png)

**Comment by nex3z** [comment]
`getCheckedIds()` returns the view ID of the checked button, instead of button position. The ID is [automatically generated](https://github.com/nex3z/ToggleButtonGroup/issues/39#issuecomment-426868383) if not specified.

To retrive checked button and/or its position, please check [here](https://github.com/nex3z/ToggleButtonGroup/issues/20#issuecomment-353236808).

**Comment by lordfarhan** [comment]
Fixed well :) thanks my man.
