### ISSUE TITLE
How can I change the text padding of MultiSelectToggleGroup?

### ISSUE THREAD

**Issue by ShimonTroiaeAbOrisWang** [nex3z/ToggleButtonGroup#51]
Default vertical padding inside `MultiSelectToggleGroup` seems way too high when `textSize` is small. And the class seems to offer no accessible function to alter it.

**Edit:** I believe I shall decrease the *corner radius* of the drawable of label buttons, and this seems not possible without recompiling the sources. Text padding can be altered with `getTextView().setPadding()` but this can only alter the padding *above a lower bound determined by the corner radius of button*.

**Comment by nex3z** [comment]
There are some examples of custom buttons in the [sample](https://github.com/nex3z/ToggleButtonGroup/tree/master/sample/src/main/java/com/nex3z/togglebuttongroup/sample/button), which are fully customizable.

For the built-in LabelToggle, use the following code to change the corner radius:

```java
MultiSelectToggleGroup multiDummy = findViewById(R.id.group_dummy);
String[] dummyText = getResources().getStringArray(R.array.dummy_text);
for (String text : dummyText) {
    LabelToggle toggle = new LabelToggle(this);
    toggle.setText(text);

    int color = ContextCompat.getColor(this, R.color.colorPrimary);
    // Background for unchecked state
    GradientDrawable unchecked = new GradientDrawable();
    unchecked.setCornerRadius(32);
    unchecked.setStroke(2, color);
    toggle.getTextView().setBackgroundDrawable(unchecked);

    // Background for checked state
    GradientDrawable checked = new GradientDrawable();
    checked.setColor(color);
    checked.setCornerRadius(32);
    checked.setStroke(2, color);
    toggle.setCheckedImageDrawable(checked);

    multiDummy.addView(toggle);
}
```

![border](https://user-images.githubusercontent.com/5645004/64164760-5b9d2980-ce76-11e9-9ff3-92b8e57f7710.png)

**Comment by ShimonTroiaeAbOrisWang** [comment]
> There are some examples of custom buttons in the [sample](https://github.com/nex3z/ToggleButtonGroup/tree/master/sample/src/main/java/com/nex3z/togglebuttongroup/sample/button), which are fully customizable.
> 
> For the built-in LabelToggle, use the following code to change the corner radius:
> 
> ```java
> MultiSelectToggleGroup multiDummy = findViewById(R.id.group_dummy);
> String[] dummyText = getResources().getStringArray(R.array.dummy_text);
> for (String text : dummyText) {
>     LabelToggle toggle = new LabelToggle(this);
>     toggle.setText(text);
> 
>     int color = ContextCompat.getColor(this, R.color.colorPrimary);
>     // Background for unchecked state
>     GradientDrawable unchecked = new GradientDrawable();
>     unchecked.setCornerRadius(32);
>     unchecked.setStroke(2, color);
>     toggle.getTextView().setBackgroundDrawable(unchecked);
> 
>     // Background for checked state
>     GradientDrawable checked = new GradientDrawable();
>     checked.setColor(color);
>     checked.setCornerRadius(32);
>     checked.setStroke(2, color);
>     toggle.setCheckedImageDrawable(checked);
> 
>     multiDummy.addView(toggle);
> }
> ```
> 
> ![border](https://user-images.githubusercontent.com/5645004/64164760-5b9d2980-ce76-11e9-9ff3-92b8e57f7710.png)
