### ISSUE TITLE
Unable to add flow buttons to single select toggle group.

### ISSUE THREAD

**Issue by Ayusch** [nex3z/ToggleButtonGroup#54]
I tried to add flow buttons to single select toggle group but was unable to do so. Also, longer text in circular button gets cut out.

Any remedies for this?

**Comment by nex3z** [comment]
There are demos about how to add buttons to toggle group in the [sample](https://github.com/nex3z/ToggleButtonGroup/tree/master/sample), both [programmatically](https://github.com/nex3z/ToggleButtonGroup/blob/master/sample/src/main/java/com/nex3z/togglebuttongroup/sample/FlowLabelActivity.java#L30) or by [xml](https://github.com/nex3z/ToggleButtonGroup/blob/master/sample/src/main/res/layout/activity_single_select.xml#L17).

For the longer text issue, feel free to build custom buttons with larger circle or smaller text.
