### ISSUE TITLE
i need different marker color and border color 

### ISSUE THREAD

**Issue by josephvijayandroiddev** [nex3z/ToggleButtonGroup#56]
i'm try this ,
 toggle.setMarkerColor(Color.parseColor("#943D53"));  this my marker color
unchecked toggle border also showing same color i need to set different  border colour...

i hope for answer ...

**Comment by nex3z** [comment]
You can build a custom button by copying code from [LabelToggle](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java) and change [line 61](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java#L61) and [line 67](https://github.com/nex3z/ToggleButtonGroup/blob/master/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/button/LabelToggle.java#L67). 

For example, 

```java
private void initBackground() {
    GradientDrawable checked = new GradientDrawable();
    checked.setColor(mMarkerColor);
    checked.setCornerRadius(dpToPx(25));
    checked.setStroke(1, Color.parseColor("#943D53")); // Change border color
    mIvBg.setImageDrawable(checked);

    GradientDrawable unchecked = new GradientDrawable();
    unchecked.setColor(ContextCompat.getColor(getContext(), android.R.color.transparent));
    unchecked.setCornerRadius(dpToPx(25));
    unchecked.setStroke((int) dpToPx(1), Color.parseColor("#943D53")); // Change border color
    mTvText.setBackgroundDrawable(unchecked);
}
```
![device-2020-01-03-170824](https://user-images.githubusercontent.com/5645004/71715391-29173380-2e4c-11ea-8a20-499ec016ded9.png)

**Comment by josephvijayandroiddev** [comment]
Thank you sir.. Happy new year..
