### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException 

### ISSUE THREAD

**Issue by ytheekshana** [nex3z/ToggleButtonGroup#57]
![image](https://user-images.githubusercontent.com/24976965/73593615-20d61500-452c-11ea-8b25-37b7c0b7e243.png)

Any Suggestions? Happens only on android 9+

**Comment by nex3z** [comment]
Could you please provide code snippet around the exception?

The "fragment not attached to a context" message suggests the exception has something to do with the fragment manipulation, eg the fragment is not properly added to its holder. Similar issue can be found [here](https://stackoverflow.com/questions/50257505/fragment-not-attached-to-a-context).
