### ISSUE TITLE
For SingleSelectToggleGroup, I am unable to "select none" after any one LabelToggle is selected

### ISSUE THREAD

**Issue by vaidyasanket** [nex3z/ToggleButtonGroup#58]
I wanted a Select None option too for SingleSelectToggleGroup. But when I click any LabelToggle, I am unable to deselect all.

**Comment by nex3z** [comment]
Do you want a "select none" label button in SingleSelectToggleGroup, or a "select none" label button in MultiSelectToggleGroup which deselect all?
