### ISSUE TITLE
In Single toggle group i need horizontal scroll it is possible?

### ISSUE THREAD

**Issue by josephvijayandroiddev** [nex3z/ToggleButtonGroup#59]

**Comment by nex3z** [comment]
Just set `android:layout_width="wrap_content"` on SingleSelectToggleGroup and put it in a HorizontalScrollView.

```xml
<HorizontalScrollView
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.nex3z.togglebuttongroup.SingleSelectToggleGroup
        android:id="@+id/group_choices"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <!--...-->
        
    </com.nex3z.togglebuttongroup.SingleSelectToggleGroup>

</HorizontalScrollView>
```

**Comment by josephvijayandroiddev** [comment]
> Just set `android:layout_width="wrap_content"` on SingleSelectToggleGroup and put it in a HorizontalScrollView.
> 
> ```
> <HorizontalScrollView
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content">
> 
>     <com.nex3z.togglebuttongroup.SingleSelectToggleGroup
>         android:id="@+id/group_choices"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content">
> 
>         
>         
>     </com.nex3z.togglebuttongroup.SingleSelectToggleGroup>
> 
> </HorizontalScrollView>
> ```

OMG i'm so stupid thank you for your honorable reply...
