### ISSUE TITLE
in single toogle group can i add image ??? like below image pls check on that

### ISSUE THREAD

**Issue by josephvijayandroiddev** [nex3z/ToggleButtonGroup#60]
![image](https://user-images.githubusercontent.com/52706576/74643868-2ea6af80-5154-11ea-9505-910e4d207635.png)

**Comment by nex3z** [comment]
You can build a custom toggle button with an extra ImageView to show the avatar. Custom button demos can be found [here](https://github.com/nex3z/ToggleButtonGroup/tree/master/sample/src/main/java/com/nex3z/togglebuttongroup/sample/button).
