### ISSUE TITLE
when i set background as grey instead of transparent my marker colur also grey clour

### ISSUE THREAD

**Issue by josephvijayandroiddev** [nex3z/ToggleButtonGroup#61]
private void initBackground() {
        GradientDrawable checked = new GradientDrawable();
        checked.setColor(Color.parseColor("#943D53"));
        checked.setCornerRadius(dpToPx(25));
        checked.setStroke(1, mMarkerColor);
        mIvBg.setImageDrawable(checked);

        GradientDrawable unchecked = new GradientDrawable();
        unchecked.setColor(/*ContextCompat.getColor(getContext(), android.R.color.transparent)*/Color.parseColor("#F5F5F5"));
        unchecked.setCornerRadius(dpToPx(25));
        unchecked.setStroke((int) dpToPx(1), Color.parseColor("#E3E3E3"));
        mTvText.setBackgroundDrawable(unchecked);
    }

**Comment by nex3z** [comment]
Set the background on the buttom itself instead on the TextView.

```java
private void initBackground() {
    GradientDrawable checked = new GradientDrawable();
    checked.setColor(Color.parseColor("#943D53"));
    checked.setCornerRadius(dpToPx(25));
    checked.setStroke(1, mMarkerColor);
    mIvBg.setImageDrawable(checked);

    // Change background
    GradientDrawable background = new GradientDrawable();
    background.setColor(Color.parseColor("#E3E3E3"));
    background.setCornerRadius(dpToPx(25));
    background.setStroke(1, mMarkerColor);
    // Set background for LabelToggle
    setBackgroundDrawable(background);

    GradientDrawable unchecked = new GradientDrawable();
    unchecked.setColor(ContextCompat.getColor(getContext(), android.R.color.transparent));
    unchecked.setCornerRadius(dpToPx(25));
    unchecked.setStroke((int) dpToPx(1), mMarkerColor);
    mTvText.setBackgroundDrawable(unchecked);
}
```

![device-2020-02-28-095217](https://user-images.githubusercontent.com/5645004/75503301-4877aa80-5a10-11ea-81e9-b6584d96b219.png)

**Comment by josephvijayandroiddev** [comment]
Thank you sir you save my day
