### ISSUE TITLE
In SingleToggleGroup i want to set one more additional id or hidden value is it possible..???

### ISSUE THREAD

**Issue by josephvijayandroiddev** [nex3z/ToggleButtonGroup#62]
Thanks in advance...

**Comment by nex3z** [comment]
Just use [`public void setTag (Object tag)`](https://developer.android.com/reference/android/view/View#setTag(java.lang.Object)) and [`public Object getTag ()`](https://developer.android.com/reference/android/view/View#getTag()), works on any `android.view.View`.
