### ISSUE TITLE
Custom CompoundToggleButton deselection issue

### ISSUE THREAD

**Issue by ytheekshana** [nex3z/ToggleButtonGroup#65]
Hello. I have created a custom CompoundToggleButton. Everything works but, when I tap the same button twice, it gets deselected. I want to deselect a button only when another button is tapped. How can i do it.

**Comment by nex3z** [comment]
You can skip toggling the button when it's already checked. 

I've updated the sample, check https://github.com/nex3z/ToggleButtonGroup/commit/aa00344f2944b6c46405b109ae3854c35590e8fe.

**Comment by ytheekshana** [comment]
Thanks. Tried it and works perfectly.
